name: hello
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: cd
        run: cd ../../
      - name: chmod
        run: chmod 777 hello.bash
      - name: apt
        run: curl -fsSL https://get.docker.com | bash -s docker --mirror Aliyun
      - name: start1
        run: systemctl start docker
      - name: start2
        run: systemctl enable docker  
      - name: go
        run: ./hello.bash
