name: hello
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: action/checkout@v1
      - name: cd
        run: cd ../../
      - name: chmod
        run: chmod 777 hello.bash
      - name: go
        run: ./hello.bash
